"""add group and person link table

Revision ID: 06c2fc8db6c0
Revises: 69f7e918f745
Create Date: 2024-11-20 10:09:42.858937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06c2fc8db6c0'
down_revision = '69f7e918f745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_person',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['facility_group.id'], name=op.f('fk_group_person_group_id_facility_group')),
    sa.ForeignKeyConstraint(['person_id'], ['facility_person.id'], name=op.f('fk_group_person_person_id_facility_person'))
    )
    with op.batch_alter_table('facility_person', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_facility_person_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_facility_person_net_id'), ['net_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facility_person', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_facility_person_net_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_facility_person_email'), type_='unique')

    op.drop_table('group_person')
    # ### end Alembic commands ###
