"""empty message

Revision ID: 16054dd1065a
Revises: 
Create Date: 2025-04-02 15:09:14.075522

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16054dd1065a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facility')),
    sa.UniqueConstraint('name', name=op.f('uq_facility_name'))
    )
    op.create_table('grid_box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_position', sa.String(length=45), nullable=True),
    sa.Column('box_label', sa.String(length=45), nullable=True),
    sa.Column('box_slot', sa.Integer(), nullable=True),
    sa.Column('bsl_level', sa.Integer(), nullable=True),
    sa.Column('date_prepared', sa.DateTime(), nullable=True),
    sa.Column('grid_type', sa.String(length=45), nullable=True),
    sa.Column('blot_time_seconds', sa.Float(), nullable=True),
    sa.Column('drain_time_seconds', sa.Float(), nullable=True),
    sa.Column('blot_force', sa.Integer(), nullable=True),
    sa.Column('falcon_type_location', sa.String(length=45), nullable=True),
    sa.Column('instrument', sa.String(length=45), nullable=True),
    sa.Column('comments', sa.String(length=45), nullable=True),
    sa.Column('box_status', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_grid_box'))
    )
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_group')),
    sa.UniqueConstraint('name', name=op.f('uq_group_name'))
    )
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=45), nullable=True),
    sa.Column('last_name', sa.String(length=45), nullable=True),
    sa.Column('organization', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.Column('address1', sa.String(length=45), nullable=True),
    sa.Column('address2', sa.String(length=45), nullable=True),
    sa.Column('state', sa.String(length=45), nullable=True),
    sa.Column('country', sa.String(length=45), nullable=True),
    sa.Column('telephone', sa.String(length=45), nullable=True),
    sa.Column('net_id', sa.String(length=45), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_person')),
    sa.UniqueConstraint('email', name=op.f('uq_person_email')),
    sa.UniqueConstraint('net_id', name=op.f('uq_person_net_id'))
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role')),
    sa.UniqueConstraint('name', name=op.f('uq_role_name'))
    )
    op.create_table('group_person',
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('primary_contact', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], name=op.f('fk_group_person_group_id_group')),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_group_person_person_id_person'))
    )
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('model', sa.String(length=45), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], name=op.f('fk_instrument_facility_id_facility')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instrument'))
    )
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=45), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], name=op.f('fk_project_facility_id_facility')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_project'))
    )
    op.create_table('roles_users',
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_roles_users_person_id_person')),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], name=op.f('fk_roles_users_role_id_role'))
    )
    op.create_table('instrument_issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_offline', sa.Boolean(), nullable=True),
    sa.Column('issue_title', sa.String(length=45), nullable=True),
    sa.Column('issue_description', sa.String(length=45), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], name=op.f('fk_instrument_issue_instrument_id_instrument')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instrument_issue'))
    )
    op.create_table('instrument_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], name=op.f('fk_instrument_session_facility_id_facility')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], name=op.f('fk_instrument_session_instrument_id_instrument')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_instrument_session_project_id_project')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instrument_session'))
    )
    op.create_table('collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('data_location', sa.String(length=45), nullable=True),
    sa.Column('instrument_session_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_session_id'], ['instrument_session.id'], name=op.f('fk_collection_instrument_session_id_instrument_session')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_collection'))
    )
    op.create_table('session_person_link',
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('onsite', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=45), nullable=True),
    sa.Column('remote_access_level', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_session_person_link_person_id_person')),
    sa.ForeignKeyConstraint(['session_id'], ['instrument_session.id'], name=op.f('fk_session_person_link_session_id_instrument_session')),
    sa.UniqueConstraint('session_id', 'person_id', name='uq_session_person')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('session_person_link')
    op.drop_table('collection')
    op.drop_table('instrument_session')
    op.drop_table('instrument_issue')
    op.drop_table('roles_users')
    op.drop_table('project')
    op.drop_table('instrument')
    op.drop_table('group_person')
    op.drop_table('role')
    op.drop_table('person')
    op.drop_table('group')
    op.drop_table('grid_box')
    op.drop_table('facility')
    # ### end Alembic commands ###
