"""field changes, after rename

Revision ID: 2ca20d14e28a
Revises: 14bfdc7f17af
Create Date: 2025-01-06 15:56:08.491894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca20d14e28a'
down_revision = '14bfdc7f17af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_person_link',
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('onsite', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=45), nullable=True),
    sa.Column('remote_access_level', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_session_person_link_person_id_person')),
    sa.ForeignKeyConstraint(['session_id'], ['instrument_session.id'], name=op.f('fk_session_person_link_session_id_instrument_session'))
    )
    op.drop_table('facility_model')
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrument_session_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_collection_instrument_session_id_instrument_session'), 'instrument_session', ['instrument_session_id'], ['id'])

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint('uq_facility_group_name', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_group_name'), ['name'])
        batch_op.drop_constraint('fk_facility_group_facility_id_facility', type_='foreignkey')
        batch_op.drop_column('facility_id')

    with op.batch_alter_table('instrument_issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrument_offline', sa.Boolean(), nullable=True))

    with op.batch_alter_table('instrument_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrument_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_instrument_session_instrument_id_instrument'), 'instrument', ['instrument_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_instrument_session_project_id_project'), 'project', ['project_id'], ['id'])

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint('uq_facility_person_email', type_='unique')
        batch_op.drop_constraint('uq_facility_person_net_id', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_person_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_person_net_id'), ['net_id'])
        batch_op.drop_constraint('fk_facility_person_group_id_facility_group', type_='foreignkey')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_facility_person_group_id_facility_group', 'group', ['group_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_person_net_id'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_person_email'), type_='unique')
        batch_op.create_unique_constraint('uq_facility_person_net_id', ['net_id'])
        batch_op.create_unique_constraint('uq_facility_person_email', ['email'])

    with op.batch_alter_table('instrument_session', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_instrument_session_project_id_project'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_instrument_session_instrument_id_instrument'), type_='foreignkey')
        batch_op.drop_column('instrument_id')

    with op.batch_alter_table('instrument_issue', schema=None) as batch_op:
        batch_op.drop_column('instrument_offline')

    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_facility_group_facility_id_facility', 'facility', ['facility_id'], ['id'])
        batch_op.drop_constraint(batch_op.f('uq_group_name'), type_='unique')
        batch_op.create_unique_constraint('uq_facility_group_name', ['name'])

    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_collection_instrument_session_id_instrument_session'), type_='foreignkey')
        batch_op.drop_column('instrument_session_id')

    op.create_table('facility_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_facility_model')
    )
    op.drop_table('session_person_link')
    # ### end Alembic commands ###
