"""add instrument_session notes field

Revision ID: 32527babb149
Revises: ffaad3803ce9
Create Date: 2026-08-28 14:29:29.439330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32527babb149'
down_revision = 'ffaad3803ce9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument_session', schema=None) as batch_op:
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
