"""empty message

Revision ID: 34c23c54a388
Revises: bce3dce5963b
Create Date: 2024-11-22 10:22:33.470581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34c23c54a388'
down_revision = 'bce3dce5963b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facility_group', schema=None) as batch_op:
        batch_op.drop_constraint('fk_facility_group_facility_id_facility', type_='foreignkey')
        batch_op.drop_column('facility_id')

    with op.batch_alter_table('facility_instrument_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility_project_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_facility_instrument_session_facility_project_id_facility_project'), 'facility_project', ['facility_project_id'], ['id'])
        batch_op.drop_column('project_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facility_instrument_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('project_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_facility_instrument_session_facility_project_id_facility_project'), type_='foreignkey')
        batch_op.drop_column('facility_project_id')

    with op.batch_alter_table('facility_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility_id', sa.INTEGER(), nullable=False))
        batch_op.create_foreign_key('fk_facility_group_facility_id_facility', 'facility', ['facility_id'], ['id'])

    # ### end Alembic commands ###
