"""empty message

Revision ID: 3a96ec28e26d
Revises: 69a4b3d18c0d
Create Date: 2025-04-02 17:30:45.313057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a96ec28e26d'
down_revision = '69a4b3d18c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_person_link', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_session_person', ['session_id', 'person_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_person_link', schema=None) as batch_op:
        batch_op.drop_constraint('uq_session_person', type_='unique')

    # ### end Alembic commands ###
