"""empty message

Revision ID: 3e9c3b51ec67
Revises: d1f4c6593dbe
Create Date: 2026-06-08 16:35:07.362296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9c3b51ec67'
down_revision = 'd1f4c6593dbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_collection_data_location'), ['data_location'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_collection_data_location'), type_='unique')

    # ### end Alembic commands ###
