"""empty message

Revision ID: 450660b71b43
Revises: 3a96ec28e26d
Create Date: 2025-04-22 10:14:53.284314

"""
from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision = '450660b71b43'
down_revision = '3a96ec28e26d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_person')
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fs_uniquifier', sa.String(length=64), nullable=True))
        batch_op.create_unique_constraint(batch_op.f('uq_person_fs_uniquifier'), ['fs_uniquifier'])

    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.String(length=100), nullable=True))

    # Custom updates
    persons = sa.table('person', sa.column('id'), sa.column('fs_uniquifier', sa.String))

    conn = op.get_bind()
    rows = conn.execute(sa.text("SELECT id FROM person")).fetchall()

    for row in rows:
        conn.execute(
            persons.update()
            .where(persons.c.id == row.id)
            .values(fs_uniquifier=str(uuid.uuid4()))
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('role', schema=None) as batch_op:
        batch_op.drop_column('description')

    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_person_fs_uniquifier'), type_='unique')
        batch_op.drop_column('fs_uniquifier')

    op.create_table('_alembic_tmp_person',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=45), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=45), nullable=True),
    sa.Column('organization', sa.VARCHAR(length=45), nullable=True),
    sa.Column('email', sa.VARCHAR(length=45), nullable=True),
    sa.Column('address1', sa.VARCHAR(length=45), nullable=True),
    sa.Column('address2', sa.VARCHAR(length=45), nullable=True),
    sa.Column('state', sa.VARCHAR(length=45), nullable=True),
    sa.Column('country', sa.VARCHAR(length=45), nullable=True),
    sa.Column('telephone', sa.VARCHAR(length=45), nullable=True),
    sa.Column('net_id', sa.VARCHAR(length=45), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('fs_uniquifier', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_facility_person'),
    sa.UniqueConstraint('email', name='uq_person_email'),
    sa.UniqueConstraint('fs_uniquifier', name='uq_person_fs_uniquifier'),
    sa.UniqueConstraint('net_id', name='uq_person_net_id')
    )
    # ### end Alembic commands ###
