"""update facility group

Revision ID: 69f7e918f745
Revises: 7c574d88bb85
Create Date: 2024-10-29 14:00:51.577794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import Inspector
# revision identifiers, used by Alembic.
revision = '69f7e918f745'
down_revision = '7c574d88bb85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = Inspector.from_engine(conn)
    if inspector.has_table('_alembic_tmp_facility_group'):
        op.execute('DROP TABLE _alembic_tmp_facility_group')

    with op.batch_alter_table('facility_group', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facility_group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
