"""add primary contact field on group_person table

Revision ID: 758af5355fee
Revises: edac137e8c68
Create Date: 2024-12-17 15:33:20.583185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758af5355fee'
down_revision = 'edac137e8c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facility_instrument_session')
    op.drop_table('facility_instrument_issue')
    op.drop_table('facility_collection')
    op.drop_table('facility_group')
    op.drop_table('facility_project')
    op.drop_table('facility_model')
    op.drop_table('facility_instrument')
    op.drop_table('facility_grid_box')
    op.drop_table('facility_person')
    with op.batch_alter_table('group_person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_contact', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_person', schema=None) as batch_op:
        batch_op.drop_column('primary_contact')

    op.create_table('facility_person',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('group_id', sa.INTEGER(), nullable=False),
    sa.Column('first_name', sa.VARCHAR(length=45), nullable=True),
    sa.Column('last_name', sa.VARCHAR(length=45), nullable=True),
    sa.Column('organization', sa.VARCHAR(length=45), nullable=True),
    sa.Column('email', sa.VARCHAR(length=45), nullable=True),
    sa.Column('address1', sa.VARCHAR(length=45), nullable=True),
    sa.Column('address2', sa.VARCHAR(length=45), nullable=True),
    sa.Column('state', sa.VARCHAR(length=45), nullable=True),
    sa.Column('country', sa.VARCHAR(length=45), nullable=True),
    sa.Column('telephone', sa.VARCHAR(length=45), nullable=True),
    sa.Column('net_id', sa.VARCHAR(length=45), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['facility_group.id'], name='fk_facility_person_group_id_facility_group'),
    sa.PrimaryKeyConstraint('id', name='pk_facility_person'),
    sa.UniqueConstraint('email', name='uq_facility_person_email'),
    sa.UniqueConstraint('net_id', name='uq_facility_person_net_id')
    )
    op.create_table('facility_grid_box',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('box_position', sa.VARCHAR(length=45), nullable=True),
    sa.Column('box_label', sa.VARCHAR(length=45), nullable=True),
    sa.Column('box_slot', sa.INTEGER(), nullable=True),
    sa.Column('bsl_level', sa.INTEGER(), nullable=True),
    sa.Column('date_prepared', sa.DATETIME(), nullable=True),
    sa.Column('grid_type', sa.VARCHAR(length=45), nullable=True),
    sa.Column('blot_time_seconds', sa.FLOAT(), nullable=True),
    sa.Column('drain_time_seconds', sa.FLOAT(), nullable=True),
    sa.Column('blot_force', sa.INTEGER(), nullable=True),
    sa.Column('falcon_type_location', sa.VARCHAR(length=45), nullable=True),
    sa.Column('instrument', sa.VARCHAR(length=45), nullable=True),
    sa.Column('comments', sa.VARCHAR(length=45), nullable=True),
    sa.Column('box_status', sa.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_facility_grid_box')
    )
    op.create_table('facility_instrument',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=45), nullable=True),
    sa.Column('model', sa.VARCHAR(length=45), nullable=True),
    sa.Column('facility_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], name='fk_facility_instrument_facility_id_facility'),
    sa.PrimaryKeyConstraint('id', name='pk_facility_instrument')
    )
    op.create_table('facility_model',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id', name='pk_facility_model')
    )
    op.create_table('facility_project',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.VARCHAR(length=45), nullable=True),
    sa.Column('facility_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], name='fk_facility_project_facility_id_facility'),
    sa.PrimaryKeyConstraint('id', name='pk_facility_project')
    )
    op.create_table('facility_group',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=45), nullable=False),
    sa.Column('facility_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], name='fk_facility_group_facility_id_facility'),
    sa.PrimaryKeyConstraint('id', name='pk_facility_group'),
    sa.UniqueConstraint('name', name='uq_facility_group_name')
    )
    op.create_table('facility_collection',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('data_location', sa.VARCHAR(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_facility_collection')
    )
    op.create_table('facility_instrument_issue',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('issue_title', sa.VARCHAR(length=45), nullable=True),
    sa.Column('issue_description', sa.VARCHAR(length=45), nullable=True),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('instrument_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['facility_instrument.id'], name='fk_facility_instrument_issue_instrument_id_facility_instrument'),
    sa.PrimaryKeyConstraint('id', name='pk_facility_instrument_issue')
    )
    op.create_table('facility_instrument_session',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('project_id', sa.INTEGER(), nullable=False),
    sa.Column('start_date', sa.DATETIME(), nullable=True),
    sa.Column('end_date', sa.DATETIME(), nullable=True),
    sa.Column('facility_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], name='fk_facility_instrument_session_facility_id_facility'),
    sa.PrimaryKeyConstraint('id', 'project_id', name='pk_facility_instrument_session')
    )
    # ### end Alembic commands ###
