"""add Instrument and session

Revision ID: 7c574d88bb85
Revises: f66684c29d06
Create Date: 2024-10-29 10:57:23.189095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c574d88bb85'
down_revision = 'f66684c29d06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('data_location', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facility_grid_box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_position', sa.String(length=45), nullable=True),
    sa.Column('box_label', sa.String(length=45), nullable=True),
    sa.Column('box_slot', sa.Integer(), nullable=True),
    sa.Column('bsl_level', sa.Integer(), nullable=True),
    sa.Column('date_prepared', sa.DateTime(), nullable=True),
    sa.Column('grid_type', sa.String(length=45), nullable=True),
    sa.Column('blot_time_seconds', sa.Float(), nullable=True),
    sa.Column('drain_time_seconds', sa.Float(), nullable=True),
    sa.Column('blot_force', sa.Integer(), nullable=True),
    sa.Column('falcon_type_location', sa.String(length=45), nullable=True),
    sa.Column('instrument', sa.String(length=45), nullable=True),
    sa.Column('comments', sa.String(length=45), nullable=True),
    sa.Column('box_status', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facility_instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('model', sa.String(length=45), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facility_instrument_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('id', 'project_id')
    )
    op.create_table('facility_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=45), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('facility_instrument_issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_title', sa.String(length=45), nullable=True),
    sa.Column('issue_description', sa.String(length=45), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['facility_instrument.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facility_instrument_issue')
    op.drop_table('facility_project')
    op.drop_table('facility_instrument_session')
    op.drop_table('facility_instrument')
    op.drop_table('facility_grid_box')
    op.drop_table('facility_collection')
    # ### end Alembic commands ###
