"""person_table branch changes

Revision ID: 882530b68728
Revises: 2ca20d14e28a
Create Date: 2025-01-06 16:09:28.866863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882530b68728'
down_revision = '2ca20d14e28a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('primary_contact', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group_person', schema=None) as batch_op:
        batch_op.drop_column('primary_contact')

    # ### end Alembic commands ###
