"""update data collections

Revision ID: 89381e768e15
Revises: debdfaf7698f
Create Date: 2026-02-22 12:00:29.002258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89381e768e15'
down_revision = 'debdfaf7698f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tiltseries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tiltseries'))
    )
    op.create_table('project_person',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('role', sa.String(45), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['person.id'], name=op.f('fk_project_person_person_id_person')),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], name=op.f('fk_project_person_project_id_project'))
    )
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_image_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('collection_type', sa.String(length=45), nullable=True))
        batch_op.alter_column('data_location',
               existing_type=sa.VARCHAR(length=45),
               type_=sa.String(length=512),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.alter_column('data_location',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=45),
               existing_nullable=True)
        batch_op.drop_column('collection_type')
        batch_op.drop_column('total_image_count')

    op.drop_table('project_person')
    op.drop_table('tiltseries')
    # ### end Alembic commands ###
