"""make project.project_id unique and dedupe project_person links

Revision ID: 9a3d5c2e7b41
Revises: b7e41c9a2f10
Create Date: 2026-09-01 12:40:07.221530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a3d5c2e7b41'
down_revision = 'b7e41c9a2f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_project_project_id', ['project_id'])

    with op.batch_alter_table('project_person', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_project_person', ['project_id', 'person_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_person', schema=None) as batch_op:
        batch_op.drop_constraint('uq_project_person', type_='unique')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_constraint('uq_project_project_id', type_='unique')

    # ### end Alembic commands ###
