"""add session_group table and link instrument_session to it

Revision ID: b7e41c9a2f10
Revises: 32527babb149
Create Date: 2026-09-01 10:12:44.185320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7e41c9a2f10'
down_revision = '32527babb149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'session_group',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=True),
        sa.Column('notes', sa.Text(), nullable=True),
        sa.Column('created_date', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instrument_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('session_group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_instrument_session_session_group_id', 'session_group', ['session_group_id'], ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instrument_session', schema=None) as batch_op:
        batch_op.drop_constraint('fk_instrument_session_session_group_id', type_='foreignkey')
        batch_op.drop_column('session_group_id')

    op.drop_table('session_group')
    # ### end Alembic commands ###
