"""Adding session_persion_link, and other table linkages

Revision ID: bce3dce5963b
Revises: 06c2fc8db6c0
Create Date: 2024-11-21 17:10:12.184204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce3dce5963b'
down_revision = '06c2fc8db6c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session_person_link',
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('person_id', sa.Integer(), nullable=True),
    sa.Column('onsite', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=45), nullable=True),
    sa.Column('remote_access_level', sa.String(length=45), nullable=True),
    sa.ForeignKeyConstraint(['person_id'], ['facility_person.id'], name=op.f('fk_session_person_link_person_id_facility_person')),
    sa.ForeignKeyConstraint(['session_id'], ['facility_instrument_session.id'], name=op.f('fk_session_person_link_session_id_facility_instrument_session'))
    )
    with op.batch_alter_table('facility_collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facility_instrument_session_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_facility_collection_facility_instrument_session_id_facility_instrument_session'), 'facility_instrument_session', ['facility_instrument_session_id'], ['id'])

    with op.batch_alter_table('facility_instrument_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrument_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_facility_instrument_session_instrument_id_facility_instrument'), 'facility_instrument', ['instrument_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facility_instrument_session', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_facility_instrument_session_instrument_id_facility_instrument'), type_='foreignkey')
        batch_op.drop_column('instrument_id')

    with op.batch_alter_table('facility_collection', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_facility_collection_facility_instrument_session_id_facility_instrument_session'), type_='foreignkey')
        batch_op.drop_column('facility_instrument_session_id')

    op.drop_table('session_person_link')
    # ### end Alembic commands ###
