"""empty message

Revision ID: c26f0cfc622d
Revises: 34c23c54a388
Create Date: 2024-11-22 10:25:12.902271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c26f0cfc622d'
down_revision = '34c23c54a388'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facility_instrument_issue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instrument_offline', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('facility_instrument_issue', schema=None) as batch_op:
        batch_op.drop_column('instrument_offline')

    # ### end Alembic commands ###
