"""widen person name/address/organization fields to 128 chars

Revision ID: c4f2a8e5d193
Revises: 9a3d5c2e7b41
Create Date: 2026-09-01 14:05:11.902441

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4f2a8e5d193'
down_revision = '9a3d5c2e7b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('first_name', existing_type=sa.String(length=45), type_=sa.String(length=128))
        batch_op.alter_column('last_name', existing_type=sa.String(length=45), type_=sa.String(length=128))
        batch_op.alter_column('organization', existing_type=sa.String(length=45), type_=sa.String(length=128))
        batch_op.alter_column('address1', existing_type=sa.String(length=45), type_=sa.String(length=128))
        batch_op.alter_column('address2', existing_type=sa.String(length=45), type_=sa.String(length=128))
        batch_op.alter_column('country', existing_type=sa.String(length=45), type_=sa.String(length=128))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.alter_column('country', existing_type=sa.String(length=128), type_=sa.String(length=45))
        batch_op.alter_column('address2', existing_type=sa.String(length=128), type_=sa.String(length=45))
        batch_op.alter_column('address1', existing_type=sa.String(length=128), type_=sa.String(length=45))
        batch_op.alter_column('organization', existing_type=sa.String(length=128), type_=sa.String(length=45))
        batch_op.alter_column('last_name', existing_type=sa.String(length=128), type_=sa.String(length=45))
        batch_op.alter_column('first_name', existing_type=sa.String(length=128), type_=sa.String(length=45))

    # ### end Alembic commands ###
