"""add remote logs

Revision ID: d1f4c6593dbe
Revises: 89381e768e15
Create Date: 2026-04-29 15:48:34.510863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1f4c6593dbe'
down_revision = '89381e768e15'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('remotesessionlog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], name=op.f('fk_remotesessionlog_instrument_id_instrument')),
    sa.ForeignKeyConstraint(['user_id'], ['person.id'], name=op.f('fk_remotesessionlog_user_id_person')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_remotesessionlog'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('remotesessionlog')
    # ### end Alembic commands ###
