"""empty message

Revision ID: debdfaf7698f
Revises: 450660b71b43
Create Date: 2025-04-24 13:28:10.301039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'debdfaf7698f'
down_revision = '450660b71b43'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_person_link', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hours', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_person_link', schema=None) as batch_op:
        batch_op.drop_column('hours')

    # ### end Alembic commands ###
