"""add collection lamella_count and editable (finalize-lock) fields

Revision ID: e1a7f3c9b2d4
Revises: c4f2a8e5d193
Create Date: 2026-09-15 09:14:02.774318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1a7f3c9b2d4'
down_revision = 'c4f2a8e5d193'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lamella_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('editable', sa.Boolean(), nullable=False, server_default=sa.true()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_column('editable')
        batch_op.drop_column('lamella_count')

    # ### end Alembic commands ###
