"""empty message

Revision ID: ea34e651abf2
Revises: 69f7e918f745
Create Date: 2024-11-05 13:09:55.467315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea34e651abf2'
down_revision = '69f7e918f745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facility')),
    sa.UniqueConstraint('name', name=op.f('uq_facility_name'))
    )
    op.create_table('facility_collection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('data_location', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facility_collection'))
    )
    op.create_table('facility_grid_box',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('box_position', sa.String(length=45), nullable=True),
    sa.Column('box_label', sa.String(length=45), nullable=True),
    sa.Column('box_slot', sa.Integer(), nullable=True),
    sa.Column('bsl_level', sa.Integer(), nullable=True),
    sa.Column('date_prepared', sa.DateTime(), nullable=True),
    sa.Column('grid_type', sa.String(length=45), nullable=True),
    sa.Column('blot_time_seconds', sa.Float(), nullable=True),
    sa.Column('drain_time_seconds', sa.Float(), nullable=True),
    sa.Column('blot_force', sa.Integer(), nullable=True),
    sa.Column('falcon_type_location', sa.String(length=45), nullable=True),
    sa.Column('instrument', sa.String(length=45), nullable=True),
    sa.Column('comments', sa.String(length=45), nullable=True),
    sa.Column('box_status', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facility_grid_box'))
    )
    op.create_table('facility_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], name=op.f('fk_facility_group_facility_id_facility')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facility_group')),
    sa.UniqueConstraint('name', name=op.f('uq_facility_group_name'))
    )
    op.create_table('facility_instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('model', sa.String(length=45), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], name=op.f('fk_facility_instrument_facility_id_facility')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facility_instrument'))
    )
    op.create_table('facility_instrument_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], name=op.f('fk_facility_instrument_session_facility_id_facility')),
    sa.PrimaryKeyConstraint('id', 'project_id', name=op.f('pk_facility_instrument_session'))
    )
    op.create_table('facility_project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.String(length=45), nullable=True),
    sa.Column('facility_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facility.id'], name=op.f('fk_facility_project_facility_id_facility')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facility_project'))
    )
    op.create_table('facility_instrument_issue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_title', sa.String(length=45), nullable=True),
    sa.Column('issue_description', sa.String(length=45), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['facility_instrument.id'], name=op.f('fk_facility_instrument_issue_instrument_id_facility_instrument')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facility_instrument_issue'))
    )
    op.create_table('facility_person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=45), nullable=True),
    sa.Column('last_name', sa.String(length=45), nullable=True),
    sa.Column('organization', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.Column('address1', sa.String(length=45), nullable=True),
    sa.Column('address2', sa.String(length=45), nullable=True),
    sa.Column('state', sa.String(length=45), nullable=True),
    sa.Column('country', sa.String(length=45), nullable=True),
    sa.Column('telephone', sa.String(length=45), nullable=True),
    sa.Column('net_id', sa.String(length=45), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['facility_group.id'], name=op.f('fk_facility_person_group_id_facility_group')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_facility_person')),
    sa.UniqueConstraint('email', name=op.f('uq_facility_person_email'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('facility_person')
    op.drop_table('facility_instrument_issue')
    op.drop_table('facility_project')
    op.drop_table('facility_instrument_session')
    op.drop_table('facility_instrument')
    op.drop_table('facility_group')
    op.drop_table('facility_grid_box')
    op.drop_table('facility_collection')
    op.drop_table('facility')
    # ### end Alembic commands ###
