"""add collection thumbnail_location

Revision ID: ffaad3803ce9
Revises: 3e9c3b51ec67
Create Date: 2026-07-30 15:32:40.168425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffaad3803ce9'
down_revision = '3e9c3b51ec67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumbnail_location', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_column('thumbnail_location')

    # ### end Alembic commands ###
